services:

  frontend:
    container_name: frontend
    build: ./frontend
    image: transcendence_frontend:dev_1.0
    pull_policy: build
    volumes:
      - ./frontend/src:/app/src
    networks:
      - transcendence_network
    restart: unless-stopped

  reverse_proxy:
    container_name: reverse_proxy
    image: nginx:1.29.8-alpine
    volumes:
      - ./reverse_proxy/templates:/etc/nginx/templates
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - NGINX_PORT=80
    networks:
      - transcendence_network
    restart: unless-stopped
    depends_on:
      - frontend
      - backend

  backend:
    container_name: backend
    build: ./backend
    image: transcendence_backend:dev_1.0
    pull_policy: build
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
    networks:
      - transcendence_network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - transcendence_network
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer:5.4.2
    networks:
      - transcendence_network
    ports:
      - 127.0.0.1:8081:8080
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  transcendence_network:
    driver: bridge
