services:

  cert_generator:
    container_name: cert_generator
    build: ./cert_generator
    image: transcendence_cert_generator:dev_1.0
    pull_policy: build
    volumes:
      - ../certs:/certs
    user: root

  frontend:
    container_name: frontend
    build: ./frontend
    image: transcendence_frontend:dev_1.0
    pull_policy: build
    volumes:
      - ./frontend/src:/app/src
    expose:
      - "5173"
    environment:
      - NGINX_PORT_EXTERNAL=${NGINX_PORT_EXTERNAL:-8443}
    networks:
      - transcendence_network
    restart: unless-stopped
    depends_on:
      cert_generator:
        condition: service_completed_successfully
      backend:
        condition: service_started

  reverse_proxy:
    container_name: reverse_proxy
    image: nginx:1.29.8-alpine
    volumes:
      - ./reverse_proxy/templates:/etc/nginx/templates
      - ../certs/reverse_proxy.key:/certs/reverse_proxy.key:ro
      - ../certs/reverse_proxy.crt:/certs/reverse_proxy.crt:ro
      - ../certs/ca.crt:/certs/ca.crt:ro
    ports:
      - "127.0.0.1:${NGINX_PORT_EXTERNAL:-8443}:${NGINX_PORT_INTERNAL:-443}"
    environment:
      - NGINX_PORT_INTERNAL=${NGINX_PORT_INTERNAL:-443}
      - NGINX_PORT_EXTERNAL=${NGINX_PORT_EXTERNAL:-8443}
    networks:
      - transcendence_network
    restart: unless-stopped
    depends_on:
      cert_generator:
        condition: service_completed_successfully
      backend:
        condition: service_started
      frontend:
        condition: service_started

  backend:
    container_name: backend
    build: ./backend
    image: transcendence_backend:dev_1.0
    pull_policy: build
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_KEY: ${CLOUDINARY_KEY}
      NGINX_PORT_EXTERNAL: ${NGINX_PORT_EXTERNAL:-8443}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
    volumes:
      - ../certs/backend.key:/certs/backend.key:ro
      - ../certs/backend.crt:/certs/backend.crt:ro
      - ../certs/ca.crt:/certs/ca.crt:ro
    networks:
      - transcendence_network
    expose:
      - "8443"
    restart: unless-stopped
    depends_on:
      cert_generator:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: >
      -c ssl=on
      -c ssl_cert_file=/certs/postgres.crt
      -c ssl_key_file=/certs/postgres.key
      -c ssl_ca_file=/certs/ca.crt
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
      - ../certs/postgres.key:/certs/postgres.key:ro
      - ../certs/postgres.crt:/certs/postgres.crt:ro
      - ../certs/ca.crt:/certs/ca.crt:ro
    networks:
      - transcendence_network
    expose:
      - "${POSTGRES_PORT_INTERNAL:-5432}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    depends_on:
      cert_generator:
        condition: service_completed_successfully

  adminer:
    container_name: adminer
    image: adminer:5.4.2
    networks:
      - transcendence_network
    ports:
      - "127.0.0.1:${ADMINER_PORT_EXTERNAL:-8081}:${ADMINER_PORT_INTERNAL:-8080}"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  transcendence_network:
    driver: bridge
