name: CI

on:
    pull_request:
        branches: [main]

jobs:
    backend-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: src/backend/go.mod

            - name: Build
              run: go build ./...
              working-directory: src/backend

    backend-lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: src/backend/go.mod

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                  version: latest
                  working-directory: src/backend

    backend-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: src/backend/go.mod

            - name: Run tests
              run: go test ./...
              working-directory: src/backend
